---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install packages
  ansible.builtin.package:
    name: "{{ openssh_packages }}"
    state: present

- name: Create configuration from template
  ansible.builtin.template:
    src: "{{ openssh_template }}"
    dest: "{{ opensshd_config }}"
    mode: "0600"
  notify: Restart openssh
  when: openssh_template is defined

- name: Convert openssh_daemon_options
  ansible.builtin.set_fact:
    openssh_daemon_options: "{{ openssh_daemon_options | dict2items }}"
  when: openssh_daemon_options | type_debug == 'dict'

- name: Update sshd settings
  ansible.builtin.lineinfile:
    path: "{{ opensshd_config }}"
    line: "{{ item.key }} {{ item.value }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    regexp: "^(#)?{{ item.key }} .*"
  loop: "{{ openssh_daemon_options }}"
  notify: Restart openssh

- name: Use specific host keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ssh/{{ item | basename }}
    mode: "{{ '0644' if item is search('\\.pub$') else '0600' }}"
  loop: "{{ openssh_host_keys }}"
  notify: Restart openssh

- name: Start the service
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    state: started
    enabled: yes

- name: Configure SELinux
  community.general.seport:
    ports: '{{ openssh_port }}'
    proto: tcp
    setype: "{{ openssh_setype }}"
    state: present
  when:
    - ansible_selinux is defined
    - ansible_selinux['status'] == 'enabled'
  notify: Restart openssh

- name: Open firewall ports
  ansible.builtin.include_role:
    name: deitkrachten.firewall
  vars:
    firewall_ports:
      - { port: "{{ openssh_port }}", proto: tcp }
