---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    openssh_port: 2222
  tasks:
    - name: Include role 'ansible-role-openssh'
      ansible.builtin.include_role:
        name: ansible-role-openssh
